build: clean
	gcc -Wall worksheet2_1.c -o ws2_1
	gcc -Wall worksheet2_2.c -o ws2_2
	gcc -Wall worksheet2_3.c -o ws2_3
	gcc -Wall worksheet2_5.c -o ws2_5
	gcc -Wall worksheet2_6.c -o ws2_6
	gcc -Wall worksheet2_7.c -o ws2_7
	gcc -Wall worksheet2_9.c -o ws2_9

clean:
	-rm ws2_1
	-rm ws2_2
	-rm ws2_3
	-rm ws2_5
	-rm ws2_6
	-rm ws2_7
	-rm ws2_9
	