link-full: build-full
	gcc -Wall worksheet4.o -o ws4_full

link-demo: build-demo
	gcc -Wall worksheet4.o -o ws4_demo

build-full:
	gcc -Wall -DFULL -c worksheet4.c

build-demo:
	gcc -Wall -DDEMO -c worksheet4.c